In [2]:
import pandas as pd
import numpy as np
data = pd.read_csv("C:\\Users\\work\\Desktop\\tencent\\pre\\user_app_actions.csv")
data.head()

   userID  installTime  appID
0       1       182032    933
1       5       141354    589
2       5       251727    565
3       5       260932    596
4       5       261318    536

In [3]:
temp = data.sort_values(by='appID')

In [7]:
temp[temp['appID']==354]

          userID  installTime  appID
4867260  2271305       301514    354
1856893   871917       132016    354
4243357  1979632       152007    354
3953292  1845041       212141    354
5650570  2639794       110040    354
2208991  1035955       101159    354
286978    135764        51647    354
752714    354828       111548    354
861472    406893        52338    354
4352868  2029880        21528    354
2740990  1283665       121124    354
2194968  1029576       101844    354
1695052   796232       142047    354
3648688  1704242       111845    354
1638739   770388       222113    354
4421185  2062117       112209    354
790585    372839       131529    354
3527314  1647141       171803    354
3537857  1651951       110911    354
5517553  2576699       260205    354
4330038  2019508        71702    354
51248      23837       102210    354
2150167  1008424       110918    354
1997921   937153        81924    354
5822458  2720605        51154    354
3284026  1535049       111840    354
4510887  2105145       110847    354
1191852   561605        11119    354
1968891   923394       260211    354
811387    382868       112126    354
...          ...          ...    ...
4446120  2073699        80832    354
4589808  2141607       121353    354
5697708  2662596       170322    354
2443094  1145327       141751    354
1017055   480591       142333    354
2417409  1133015       112204    354
168252     80240       110940    354
3392730  1584488       111454    354
3062846  1433609        82122    354
171208     81624       152236    354
5001268  2333923       290109    354
5852794  2734442       250845    354
1906617   894769       121140    354
5321607  2483168       102252    354
891704    421645       111716    354
59176      27893       181311    354
3055521  1429918        41500    354
594981    282584       252213    354
3425349  1599310       132029    354
4148322  1935460        61948    354
891576    421543       120035    354
1202905   567048       121615    354
3044414  1424828       260425    354
3577842  1670626       120750    354
201652     95867       171758    354
1171538   551961        31905    354
4553702  2124981       280010    354
2926099  1369632       171850    354
116330     55835       170714    354
4988575  2327875       161943    354

[2120 rows x 3 columns]