In [2]:
import pandas as pd
import numpy as np
data = pd.read_csv("C:\\Users\\work\\Desktop\\tencent\\pre\\user_app_actions.csv")
data.head()

   userID  installTime  appID
0       1       182032    933
1       5       141354    589
2       5       251727    565
3       5       260932    596
4       5       261318    536

In [3]:
temp = data.sort_values(by='appID')

In [4]:
temp.head()

          userID  installTime   appID
4867260  2271305       301514     354
1856893   871917       132016     354
4243357  1979632       152007     354
3953292  1845041       212141     354
5650570  2639794       110040     354
2208991  1035955       101159     354
286978    135764        51647     354
752714    354828       111548     354
861472    406893        52338     354
4352868  2029880        21528     354
2740990  1283665       121124     354
2194968  1029576       101844     354
1695052   796232       142047     354
3648688  1704242       111845     354
1638739   770388       222113     354
4421185  2062117       112209     354
790585    372839       131529     354
3527314  1647141       171803     354
3537857  1651951       110911     354
5517553  2576699       260205     354
4330038  2019508        71702     354
51248      23837       102210     354
2150167  1008424       110918     354
1997921   937153        81924     354
5822458  2720605        51154     354
3284026  1535049       111840     354
4510887  2105145       110847     354
1191852   561605        11119     354
1968891   923394       260211     354
811387    382868       112126     354
...          ...          ...     ...
5086607  2374321       182238  432747
455340    216552       131853  432846
2984608  1396820       102034  432861
2446098  1146765        82124  432886
4176991  1948970        52200  432897
3070542  1436777       261423  432909
5135860  2397270        31413  432911
5409024  2525141        31618  432916
5758674  2690804       121022  432930
2575400  1206585       171540  432931
1609702   757203       291220  432971
1347701   633989       172344  432973
2614287  1225352        31307  432985
5485084  2561723       160647  433003
3120796  1459405        51358  433029
1493911   702400       261641  433056
1186835   559053       240522  433059
3456854  1614426        71515  433076
3635542  1698144       210222  433114
1609396   757094        80717  433138
5265868  2457131        20833  433156
2626866  1230557       222019  433158
1719674   807590       230308  433167
4211520  1965000        21846  433174
168373     80288        31637  433189
5115915  2387955       161517  433198
1719675   807590       230308  433221
5108508  2384529       121447  433258
538420    255801        41840  433261
641107    304254       280008  433267

[6003471 rows x 3 columns]